/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionButton: typeof import('./src/components/ActionButton.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    BetweenMenus: typeof import('./src/components/BetweenMenus.vue')['default']
    CardOperator: typeof import('./src/components/CardOperator.vue')['default']
    CardPanel: typeof import('./src/components/CardPanel.vue')['default']
    CopyButton: typeof import('./src/components/CopyButton.vue')['default']
    DataStatistic: typeof import('./src/components/DataStatistic.vue')['default']
    IconBtn: typeof import('./src/components/IconBtn.vue')['default']
    InnerCard: typeof import('./src/components/InnerCard.vue')['default']
    InputDialogProvider: typeof import('./src/components/InputDialogProvider.vue')['default']
    LayoutCard: typeof import('./src/components/LayoutCard.vue')['default']
    LeftMenuBtn: typeof import('./src/components/LeftMenuBtn.vue')['default']
    LeftMenusPanel: typeof import('./src/components/LeftMenusPanel.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    MyselfInfoDialog: typeof import('./src/components/MyselfInfoDialog.vue')['default']
    NewCardList: typeof import('./src/components/NewCardList/index.vue')['default']
    NodeSimpleChart: typeof import('./src/components/NodeSimpleChart.vue')['default']
    Params: typeof import('./src/components/NewCardList/params.vue')['default']
    PlaceHolderCard: typeof import('./src/components/PlaceHolderCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
