#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ -z ${LSIO_NON_ROOT_USER} ]]; then
exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 24444" \
        cd /opt/mcsmanager/daemon s6-setuidgid abc node --max-old-space-size=8192 --enable-source-maps app.js
else
exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 24444" \
        cd /opt/mcsmanager/daemon node --max-old-space-size=8192 --enable-source-maps app.js
fi
